server:
  port: 8084

spring:
  application:
    name: user-mgmt-api
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&interactiveClient=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.your.package: TRACE